export const SCENE_CONFIG = {
    TERRAIN_SIZE: 10.0,
    TERRAIN_HEIGHT: 8.0,
    CAMERA_FOV: 50,
    CAMERA_NEAR: 0.1,
    CAMERA_FAR: 100,
    CAMERA_DISTANCE: 22,
    CAMERA_ELEVATION: 30,
    CAMERA_LOOK_AT: { x: 0, y: 1, z: 0 },
    MAX_PIXEL_RATIO: 1.5,
    GRID_SIZE_MULTIPLIER: 1.4,
    GRID_DIVISIONS: 28,
    GRID_OPACITY: 0.9,
    GRID_Y_OFFSET: -0.02,
} as const;

export const LIGHTING_CONFIG = {
    AMBIENT_INTENSITY: 0.2,
    DIR_LIGHT_1_INTENSITY: 1.0,
    DIR_LIGHT_1_POSITION: { x: 5, y: 10, z: 5 },
    DIR_LIGHT_2_INTENSITY: 0.6,
    DIR_LIGHT_2_POSITION: { x: -5, y: 8, z: -5 },
    TERRAIN_BRIGHTEN: 2.2,
    TERRAIN_EMISSIVE_INTENSITY: 0.95,
} as const;

export const MARKER_CONFIG = {
    POLE_HEIGHT: 2.0,
    HEAD_RADIUS: 0.12,
    HEAD_SEGMENTS: { width: 16, height: 12 },
    GLOW_INNER_RADIUS: 0.1,
    GLOW_OUTER_RADIUS: 0.15,
    GLOW_SEGMENTS: 24,
    BASE_RADIUS: 0.15,
    BASE_SEGMENTS: 16,
    HITBOX_RADIUS: 0.3,
    HITBOX_SEGMENTS: 8,
    PATH_DASH_SIZE: 0.25,
    PATH_GAP_SIZE: 0.12,
    PATH_Y_OFFSET: 0.05,
    MAX_MARKERS: 50,
} as const;

export const ANIMATION_CONFIG = {
    TIME_STEP: 0.016,
    ORBIT_SPEED: 0.04,
    ORBIT_RADIUS: 15,
    CAMERA_Y_BASE: 9,
    CAMERA_Y_AMPLITUDE: 1.5,
    CAMERA_Y_FREQUENCY: 0.08,
    PULSE_FREQUENCY: 2.5,
    PULSE_PHASE_SHIFT: 0.5,
    MARKER_HOVER_SCALE: 1.4,
    MARKER_NORMAL_SCALE: 1,
    SCALE_LERP_SPEED: 0.1,
    MARKER_FLOAT_FREQUENCY: 1.5,
    MARKER_FLOAT_AMPLITUDE: 0.03,
    RAYCAST_THROTTLE: 3,
    CONTOUR_ANIMATION_THROTTLE: 2,
} as const;

export const POST_PROCESSING_CONFIG = {
    BLOOM_RESOLUTION_DIVISOR: 2,
    BLOOM_STRENGTH: 0.3,
    BLOOM_RADIUS: 0.4,
    BLOOM_THRESHOLD: 0.85,
} as const;
